name: MTVehicles
version: 2.2
main: nl.mtvehicles.core.Main
api-version: 1.13
commands:
  minetopiavehicles:
    usage: /minetopiavehicles
    aliases: [ mtv, minetopiav, mtvehicles, mtvehicle, vehicle ]
