name: MTVehicles
version: 2.0.7
main: nl.mtvehicles.core.Main
api-version: 1.13
softdepend:
  - ProtocolLib
commands:
  minetopiavehicles:
    usage: /minetopiavehicles
    aliases: [ mtv, minetopiav, mtvehicles, vehicle ]