name: MinetopiaVehicles
version: 1.0.0
main: nl.mtvehicles.core.Main

softdepend:
  - ProtocolLib

commands:
  minetopiavehicles:
    usage: /minetopiavehicles
    aliases: [ mtv, minetopiav, mtvehicles, vehicle ]